# Generated by Django 4.1.3 on 2022-12-03 18:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=None, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='date_ceated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=None, unique=2)),
                ('author', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(upload_to='media/blog/featured_images')),
                ('blog_content', ckeditor.fields.RichTextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default='uncategorised', on_delete=django.db.models.deletion.SET_DEFAULT, to='website.category')),
            ],
        ),
    ]
