# Generated by Django 4.1.3 on 2022-12-03 18:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
