# Generated by Django 4.1.3 on 2022-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blog_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='blog/featured_images'),
        ),
    ]
