# Generated by Django 4.1.3 on 2022-12-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='author',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='feature_summary',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='status',
        ),
        migrations.AddField(
            model_name='feature',
            name='article_link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='date_featured',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='news_paper',
            field=models.TextField(default='Igihe', max_length=255),
        ),
    ]
